# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b0a5ec9ee656aa9b239eaaf8d7694e2b712ed27533a647770bca7aa906837836242bbccd2315b1ba76ee456ab2470717062c72d8b484ae511f2c7cbe1e864b5

test:
  secret_key_base: 20a3d5604f18378212f700faec05018ac01ddd657530abb048857bab588dff4b66723569d19e4b14289a73ccbba3a02c55af8121611a3dca34b28906b93518a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
